server:
  #服务端口号
  port: 8012
  #servlet:
    #context-path: /pesservice01
spring:
  application:
    # 服务名称 - 服务之间使用名称进行通讯
    name: pes-service-01
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    circuitbreaker:
      hystrix:
        enabled: true
eureka:
  client:
    service-url:
      # 填写注册中心服务器地址
      defaultZone: http://127.0.0.1:7012/eureka
    # 是否需要将自己注册到注册中心
    register-with-eureka: true
    # 是否需要搜索服务信息
    fetch-registry: true
  instance:
    # 使用ip地址注册到注册中心
    prefer-ip-address: true
    # 注册中心列表中显示的状态参数
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
# Timeout单位为ms  1000即为1S
feign:
  client:
    config:
      default:
        #请求连接超时时间
        connectTimeout: 5000
        #请求处理超时时间
        readTimeout: 5000

hystrix:
  command:
    default:
      execution:
        isolation:
           thread:
               timeoutInMilliseconds: 3000
  dashboard:
    proxy-stream-allow-list: "127.0.0.1"
