server:
  # 配置服务端口
  port: 7018
eureka:
  client:
    service-url:
      # 填写注册中心服务器地址
      defaultZone: http://127.0.0.1:7012/eureka
    # 是否需要将自己注册到注册中心
    register-with-eureka: true
    # 是否需要搜索服务信息
    fetch-registry: true
  instance:
    # 使用ip地址注册到注册中心
    prefer-ip-address: true
    # 注册中心列表中显示的状态参数
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
spring:
  application:
    # 服务名称 - 服务之间使用名称进行通讯
    name: pes-gateway
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  cloud:
    gateway:
      routes:
        #cookie断言 postman测试访问 http://127.0.0.1:7018/pesTestController01/test01 请求头增加Cookie ： tname=zhangsan 路由到http://127.0.0.1:8012/pesTestController01/test01
        - id: cookie-proxy-1
          uri: http://127.0.0.1:8012/
          predicates:
            - Cookie=tname, zhangsan
        # postman访问 http://127.0.0.1:7018/pesservice01/pesTestController01/test01 路由到http://127.0.0.1:8012/pesTestController01/test01
        - id: pes-service-01-proxy
          uri: http://127.0.0.1:8012/
          predicates:
            - Path=/pesservice01/**
          #因为pesservice01项目没配置项目名(默认root)，ip 端口号直接访问的 通过filters StripPrefix=1截取到Path断言默认追加的pesservice01路径
          filters:
            - StripPrefix=1

